doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Post\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Post/Entity'
                prefix: 'App\Post\Entity'
                alias: App
            App\Person\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Person/Entity'
                prefix: 'App\Person\Entity'
                alias: App
            App\Comment\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Comment/Entity'
                prefix: 'App\Comment\Entity'
                alias: App
